export const ADD_EXPENSE_COPY = {
  addingButton: "Adding\u2026",
  addItemButton: "Add item",
  amountInvalid: "Enter a positive amount",
  amountLabel: "Amount",
  amountPlaceholder: "0.00",
  assignedToLabel: "Assigned to",
  cancelButton: "Cancel",
  descriptionLabel: "Description",
  descriptionPlaceholder: "e.g. Dinner, Hotel, Taxi",
  descriptionRequired: "Description is required",
  equalSplitLabel: "Equal split",
  itemAmountInvalid: "Each line item must have a positive amount",
  itemAmountLabel: "Amount",
  itemAmountPlaceholder: "0.00",
  itemDescriptionLabel: "Description",
  itemDescriptionPlaceholder: "e.g. Salad",
  itemDescriptionRequired: "Each line item must have a description",
  itemizedSplitLabel: "Itemized",
  itemizedSubtotalMismatch:
    "Subtotal + tax + tip does not match the total amount",
  loading: "Loading\u2026",
  noMembersEmptyState:
    "Add at least one trip member before creating an expense.",
  noMembersGoBackLink: "Go back to manage members",
  noMembersPaidByPlaceholder: "Add trip members to choose who paid",
  paidByLabel: "Paid by",
  removeItemButton: "Remove",
  splitAmongLabel: "Split among",
  splitAmongRequired: "Select at least one member",
  splitTypeLabel: "Split type",
  submitButton: "Add Expense",
  subtitle: "Record a new expense for this trip",
  taxLabel: "Tax",
  tipLabel: "Tip",
  title: "Add Expense",
} as const;
