export const AUTH_COPY = {
  signIn: {
    title: "Sign in",
    description: "Enter your email and password to sign in.",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    submitButton: "Sign in",
    noAccount: "Don't have an account?",
    signUpLink: "Sign up",
  },
  signUp: {
    title: "Create an account",
    description: "Enter your details to get started.",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm password",
    submitButton: "Create account",
    hasAccount: "Already have an account?",
    signInLink: "Sign in",
  },
  errors: {
    emailRequired: "Email is required.",
    emailInvalid: "Please enter a valid email address.",
    passwordRequired: "Password is required.",
    passwordTooShort: "Password must be at least 6 characters.",
    passwordMismatch: "Passwords do not match.",
    wrongPassword: "Incorrect password. Please try again.",
    userNotFound: "No account found with this email.",
    emailAlreadyInUse: "An account with this email already exists.",
    tooManyRequests: "Too many attempts. Please try again later.",
    generic: "Something went wrong. Please try again.",
  },
} as const;
