export const AUTH_COPY = {
  signIn: {
    title: "Sign in",
    description: "Enter your email and password to sign in.",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    submitButton: "Sign in",
    submittingButton: "Signing in\u2026",
    noAccount: "Don't have an account?",
    signUpLink: "Sign up",
  },
  signUp: {
    title: "Create an account",
    description: "Enter your details to get started.",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm password",
    submitButton: "Create account",
    submittingButton: "Creating account\u2026",
    hasAccount: "Already have an account?",
    signInLink: "Sign in",
  },
  errors: {
    accountExistsWithDifferentCredential:
      "An account already exists with this email using a different sign-in method.",
    emailAlreadyInUse: "An account with this email already exists.",
    emailInvalid: "Please enter a valid email address.",
    emailRequired: "Email is required.",
    generic: "Something went wrong. Please try again.",
    invalidCredential: "Invalid email or password.",
    networkError: "Check your internet connection and try again.",
    passwordMismatch: "Passwords do not match.",
    passwordRequired: "Password is required.",
    passwordTooShort: "Password must be at least 6 characters.",
    popupClosedByUser: "Sign-in was cancelled. Please try again.",
    tooManyRequests: "Too many attempts. Please try again later.",
  },
  google: {
    signInButton: "Sign in with Google",
    signUpButton: "Sign up with Google",
    orDivider: "or",
  },
} as const;
